name: Website

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true


on:
  workflow_call:
    inputs:
      java-distribution:
        description: JDK vendor (zulu, temurin, etc.)
        type: string
        default: zulu
      java-version:
        description: Java version to setup (25)
        type: number
        default: 25
      memory-limit:
        description: Memory limit for sbt (2048 MB)
        type: number
        default: 2048
      cache-key:
        description: Cache key
        type: string
        default: "target"
      node-version:
        description: Node version to setup (23)
        type: number
        default: 23
      script:
        description: Test command to run
        type: string
        default: ./scripts/gh-pages.sh'
      publish:
        description: Whether to deploy the website
        type: boolean
        default: true





jobs:
  website:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
       - name: Checkout code
         uses: actions/checkout@v6

       - name: Fetch tags
         run: git fetch --prune --unshallow --tags        

       - name: Setup Graphviz
         uses: ts-graphviz/setup-graphviz@v2

       - name: Set up Node
         uses: actions/setup-node@v6
         with:
          node-version: ${{ inputs.node-version }}

       - name: Set up SBT
         uses: /WorldOfScala/actions/setup-sbt@master
         with:
           distribution: ${{ inputs.java-distribution }}
           java-version: ${{ inputs.java-version }}

       - name: Restore compilation cache
         if: ${{ inputs.cache-key != '' && !contains(github.event.pull_request.body, 'ci:skip-cache') }}
         uses: /WorldOfScala/actions/restore-compilation-cache@master
         with:
            key: ${{ inputs.cache-key }}
       - name: Compile (main & tests)
         shell: bash
#         run: VERSION=`git describe --tags --abbrev=0 | sed "s/v//"` sbt '${{ inputs.command }}'
         run: ${{ inputs.script }}

       - name: Setup Pages
         uses: actions/configure-pages@v5
       - name: Upload artifact
         if: ${{ inputs.publish }}
         uses: actions/upload-pages-artifact@v4
         with:
            path: "target/site"
       - name: Deploy to GitHub Pages
         if: ${{ inputs.publish }}
         id: deployment
         uses: actions/deploy-pages@v4 



